# Generated by Django 4.0 on 2021-12-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
